### ISSUE TITLE
Move website and documentation issues to this repo

### ISSUE THREAD

**Issue by dashohoxha** [numpy/numpy.org#27] opened 2019-07-18 09:16 UTC
I think that it would be nice if documentation issues are kept on this repo as well (or on their own repo), instead of discussing them on numpy/numpy. This would clearly distinguish them from the rest of the issues (bugs, features, enhancements, etc.).

For example I am interested on the website and documentation issues, but I have to subscribe (watch) to numpy/numpy. As a result I get more than 100 notification messages a day, 90% of which I have to delete because I am not interested in them (actually I don't understand what is being discussed there). This is like a kind of innocent spam. A better classification of issues to different repositories may help to reduce this.

**Note**: Maybe the same should be done for scipy too.

**Comment by rgommers** [comment] 2019-07-18 15:03
This isn't really feasible - there's too much overlap between docs and code, and issues should be on the repo that contains the content that the issue is about.

What we can do though is to make it much easier to filter the messages. Setting up filters in the right way can be tricky, so documenting a standard one with e.g. Gmail would be handy.

**Comment by dashohoxha** [comment] 2019-07-18 15:56
At least we can keep the website issues here, if the website maintenance is not much related with development+documentation work.

**Comment by joelachance** [comment] 2019-08-07 22:08
Can we close this one?

**Comment by rgommers** [comment] 2019-08-07 22:16
Yes we can. Website issues are already on this repo, so nothing left to do. Thanks @dashohoxha and @joelachance

**Closed by rgommers** 2019-08-07 22:16 UTC
