### ISSUE TITLE
Homepage - Case studies - Layout/Design

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#129] opened 2020-01-06 05:13 UTC
Add the ‘Case studies’ segment below 'In a nutshell' using a tile layout grid and link to the case study/studies.

**Comment by InessaPawson** [comment] 2020-01-06 09:39
@joelachance, could you implement this layout https://github.com/numpy/numpy.org/issues/82#issuecomment-571007398?

**Comment by joelachance** [comment] 2020-01-06 13:25
Yep! Still finishing some interactive shell stuff, but i'll work on some layout improvements next.

**Comment by joelachance** [comment] 2020-01-08 16:05
@InessaPawson, I'm going to close this issue, it seems to be a duplicate of #82.

**Comment by rgommers** [comment] 2020-02-16 02:20
done in gh-159, closing

**Closed by rgommers** 2020-02-16 02:20 UTC
Labels: design
