### ISSUE TITLE
BUG: overlapping links on landing page

### ISSUE THREAD

**Issue by bsipocz** [numpy/numpy.org#705] opened 2023-12-06 18:51 UTC
Minor rendering(?) issue that I see both from firefox and chrome
<img width="141" alt="Screenshot 2023-12-06 at 10 50 18" src="https://github.com/numpy/numpy.org/assets/6788290/70e96c7b-525c-435c-8f25-f76f3810e0a8">

**Comment by stefanv** [comment] 2023-12-06 18:53
I can't reproduce; @alphapapa @jarrodmillman?

@bsipocz does zooming in and out affect anything?

**Comment by bsipocz** [comment] 2023-12-06 19:00
> does zooming in and out affect anything?

Unfortunately not, zoomed out to 200% in both browsers and it still overlaps. Maybe it's different fontsets on OSX? Weirdly all the other topics are fine as all of those fit in one line. Maybe we could use their abbreviation, CEA?

**Comment by WarrenWeckesser** [comment] 2023-12-06 20:25
I can reproduce the overlap on a Mac with Firefox.

**Comment by alphapapa** [comment] 2023-12-06 20:32
Will investigate today.  Thanks.

**Comment by alphapapa** [comment] 2023-12-07 01:02
This will be fixed by my branch which refactors this tab.  I've rebased it and made a PR.  Please see https://github.com/numpy/numpy.org/pull/706.

**Closed** 2023-12-07 01:12 UTC

**Comment by stefanv** [comment] 2023-12-07 18:46
@bsipocz Can you please confirm that this is now fixed?

**Comment by bsipocz** [comment] 2023-12-07 19:36
Yes, it's all fixed. Thank you for the very fast bugfix cycle!
